### ISSUE TITLE
Feature Request: Top-up Functionality

### ISSUE THREAD

**Issue by eugenevdm** [eksoverzero/whmcs-freeradius#4]
It would be great if topping up functionality could be added.

**Comment by dontforget** [comment]
Is there any ETA?

Thanks!

**Comment by eksoverzero** [comment]
Hi. So it turns out, this wasn't actually removed. It's just not documented. 

Basically, it works using product configuration groups. http://docs.whmcs.com/Addons_and_Configurable_Options

The implementation was very basic so the naming of the config option as to be exactly "X Megabytes" or "X Gigabytes", "X" being a number.
